### ISSUE TITLE
ability to edit the configuration file

### ISSUE THREAD

**Issue by gsi095** [hassio-addons/addon-aircast#6]
# Problem/Motivation

> To allow speakers with both Airplay and Chromecast built in to be excluded so it doesnt create duplicate airplay destinations for the same device in Aircast

## Expected behavior

> enable renaming and excluding speakers, also set other settings in the config file

## Actual behavior

> cannot edit config file

## Steps to reproduce

> align the addon with the regular application which allows config file modification

## Proposed changes

> align the addon with the regular application which allows config file modification

**Comment by gsi095** [comment]
Aligning the has.io addon with the regular application would make the addon complete, without it I cannot use the addon (which Id prefer) as I need to edit the config file.

**Comment by jjanderson** [comment]
Firstly, have to say I love this add-on... makes life very easy when the wife only uses her iPhone, so not only does this do what it says on the tin, it contributes to both home automation and harmony! 

It would be great as a future enhancement to be able to exclude certain devices as per this note so as to exclude devices with built in Chromecast and Airplay... 

Otherwise, thanks for an awesome add-on!

**Comment by frenck** [comment]
Added in `v0.6.0`.
